apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: application-db
spec:
  replicas: 1
  selector:
    matchLabels:
      database: applicationdb
  template:
    metadata:
      labels:
        database: applicationdb
    spec:
      containers:
      - name: application-db
        image:  mongo:3.3
        env:
        - name: MONGODB_DATABASE
          value: rsvpdata
        ports:
        - containerPort: 27017